'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class English
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("HA.English", GetType(English).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The .
        '''</summary>
        Friend Shared ReadOnly Property resArticleThe() As String
            Get
                Return ResourceManager.GetString("resArticleThe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You talk to yourself for a moment... pretty boring..
        '''</summary>
        Friend Shared ReadOnly Property resChatSelf() As String
            Get
                Return ResourceManager.GetString("resChatSelf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You close the door..
        '''</summary>
        Friend Shared ReadOnly Property resCloseDoor() As String
            Get
                Return ResourceManager.GetString("resCloseDoor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You can&apos;t close the door. The .
        '''</summary>
        Friend Shared ReadOnly Property resCloseDoorBlocked1() As String
            Get
                Return ResourceManager.GetString("resCloseDoorBlocked1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to is in the way..
        '''</summary>
        Friend Shared ReadOnly Property resCloseDoorBlocked2() As String
            Get
                Return ResourceManager.GetString("resCloseDoorBlocked2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Don&apos;t be silly, you can&apos;t close yourself!.
        '''</summary>
        Friend Shared ReadOnly Property resCloseDoorSelf() As String
            Get
                Return ResourceManager.GetString("resCloseDoorSelf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thud! You run into the door. .
        '''</summary>
        Friend Shared ReadOnly Property resCollideDoor() As String
            Get
                Return ResourceManager.GetString("resCollideDoor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thud! You run into the wall. .
        '''</summary>
        Friend Shared ReadOnly Property resCollideWall() As String
            Get
                Return ResourceManager.GetString("resCollideWall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You cannot think clearly enough to aim. .
        '''</summary>
        Friend Shared ReadOnly Property resConfusedAim() As String
            Get
                Return ResourceManager.GetString("resConfusedAim", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You do not possess the necessary focus to cast spells. .
        '''</summary>
        Friend Shared ReadOnly Property resConfusedCast() As String
            Get
                Return ResourceManager.GetString("resConfusedCast", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You attempt to speak, but can only babble. .
        '''</summary>
        Friend Shared ReadOnly Property resConfusedChat() As String
            Get
                Return ResourceManager.GetString("resConfusedChat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Closing the door proves to be too great a challenge right now. .
        '''</summary>
        Friend Shared ReadOnly Property resConfusedCloseDoor() As String
            Get
                Return ResourceManager.GetString("resConfusedCloseDoor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not while confused. .
        '''</summary>
        Friend Shared ReadOnly Property resConfusedDefault() As String
            Get
                Return ResourceManager.GetString("resConfusedDefault", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You see a bunch of stuff, but none of it makes sense. .
        '''</summary>
        Friend Shared ReadOnly Property resConfusedInventory() As String
            Get
                Return ResourceManager.GetString("resConfusedInventory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This door seems too complicated in your current state. .
        '''</summary>
        Friend Shared ReadOnly Property resConfusedOpenDoor() As String
            Get
                Return ResourceManager.GetString("resConfusedOpenDoor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You search haphazardly, but find nothing. .
        '''</summary>
        Friend Shared ReadOnly Property resConfusedSearch() As String
            Get
                Return ResourceManager.GetString("resConfusedSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are having trouble remembering the activation word. .
        '''</summary>
        Friend Shared ReadOnly Property resConfusedZap() As String
            Get
                Return ResourceManager.GetString("resConfusedZap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  You die. .
        '''</summary>
        Friend Shared ReadOnly Property resDeathMsg() As String
            Get
                Return ResourceManager.GetString("resDeathMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ugh! The door is stuck. .
        '''</summary>
        Friend Shared ReadOnly Property resDoorStuck() As String
            Get
                Return ResourceManager.GetString("resDoorStuck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This tunnel has been flooded for some time....
        '''</summary>
        Friend Shared ReadOnly Property resFloodedTunnel() As String
            Get
                Return ResourceManager.GetString("resFloodedTunnel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You may not cross that terrain..
        '''</summary>
        Friend Shared ReadOnly Property resImpassable() As String
            Get
                Return ResourceManager.GetString("resImpassable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -------------------------------- Items on Ground --------------------------------.
        '''</summary>
        Friend Shared ReadOnly Property resItemsGround() As String
            Get
                Return ResourceManager.GetString("resItemsGround", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pick up item .
        '''</summary>
        Friend Shared ReadOnly Property resItemsPickup() As String
            Get
                Return ResourceManager.GetString("resItemsPickup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to or z to exit..
        '''</summary>
        Friend Shared ReadOnly Property resItemsZToExit() As String
            Get
                Return ResourceManager.GetString("resItemsZToExit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Heroic Adventure! KeyBindings.
        '''</summary>
        Friend Shared ReadOnly Property resKeybindingsTitle() As String
            Get
                Return ResourceManager.GetString("resKeybindingsTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You kick the door, .
        '''</summary>
        Friend Shared ReadOnly Property resKickDoor() As String
            Get
                Return ResourceManager.GetString("resKickDoor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to but nothing happens..
        '''</summary>
        Friend Shared ReadOnly Property resKickDoorNothing() As String
            Get
                Return ResourceManager.GetString("resKickDoorNothing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to and smash it to pieces..
        '''</summary>
        Friend Shared ReadOnly Property resKickDoorSmash() As String
            Get
                Return ResourceManager.GetString("resKickDoorSmash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  You kick at the .
        '''</summary>
        Friend Shared ReadOnly Property resKickMiss1() As String
            Get
                Return ResourceManager.GetString("resKickMiss1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  but you miss. .
        '''</summary>
        Friend Shared ReadOnly Property resKickMiss2() As String
            Get
                Return ResourceManager.GetString("resKickMiss2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wham! You kick the .
        '''</summary>
        Friend Shared ReadOnly Property resKickMonsterHit() As String
            Get
                Return ResourceManager.GetString("resKickMonsterHit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  You kick at nothing with all your might. .
        '''</summary>
        Friend Shared ReadOnly Property resKickNothing() As String
            Get
                Return ResourceManager.GetString("resKickNothing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You kick yourself. Feel better?.
        '''</summary>
        Friend Shared ReadOnly Property resKickSelf() As String
            Get
                Return ResourceManager.GetString("resKickSelf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You kick the wall..
        '''</summary>
        Friend Shared ReadOnly Property resKickWall() As String
            Get
                Return ResourceManager.GetString("resKickWall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Owww! You glare at the wall..
        '''</summary>
        Friend Shared ReadOnly Property resKickWallFail() As String
            Get
                Return ResourceManager.GetString("resKickWallFail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You reduce the wall to rubble..
        '''</summary>
        Friend Shared ReadOnly Property resKickWallRubble() As String
            Get
                Return ResourceManager.GetString("resKickWallRubble", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  poison .
        '''</summary>
        Friend Shared ReadOnly Property resKilledByPoison() As String
            Get
                Return ResourceManager.GetString("resKilledByPoison", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This area is completely dark..
        '''</summary>
        Friend Shared ReadOnly Property resLookDark() As String
            Get
                Return ResourceManager.GetString("resLookDark", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There is a pile of items here..
        '''</summary>
        Friend Shared ReadOnly Property resLookItemsPile() As String
            Get
                Return ResourceManager.GetString("resLookItemsPile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You don&apos;t know anything about this place..
        '''</summary>
        Friend Shared ReadOnly Property resLookUnknown() As String
            Get
                Return ResourceManager.GetString("resLookUnknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  feet. .
        '''</summary>
        Friend Shared ReadOnly Property resMeasurementFeet() As String
            Get
                Return ResourceManager.GetString("resMeasurementFeet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  is about to die. .
        '''</summary>
        Friend Shared ReadOnly Property resMonsterAboutToDie() As String
            Get
                Return ResourceManager.GetString("resMonsterAboutToDie", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  is dead. .
        '''</summary>
        Friend Shared ReadOnly Property resMonsterDead() As String
            Get
                Return ResourceManager.GetString("resMonsterDead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  is destroyed. .
        '''</summary>
        Friend Shared ReadOnly Property resMonsterDestroyed() As String
            Get
                Return ResourceManager.GetString("resMonsterDestroyed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  has minor wounds. .
        '''</summary>
        Friend Shared ReadOnly Property resMonsterMinorWounds() As String
            Get
                Return ResourceManager.GetString("resMonsterMinorWounds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  has a few scratches. .
        '''</summary>
        Friend Shared ReadOnly Property resMonsterScratches() As String
            Get
                Return ResourceManager.GetString("resMonsterScratches", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  is seriously wounded..
        '''</summary>
        Friend Shared ReadOnly Property resMonsterSeriousWounds() As String
            Get
                Return ResourceManager.GetString("resMonsterSeriousWounds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There is nobody to talk to. .
        '''</summary>
        Friend Shared ReadOnly Property resNobodyToChat() As String
            Get
                Return ResourceManager.GetString("resNobodyToChat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You may not cross that terrain (yet)..
        '''</summary>
        Friend Shared ReadOnly Property resNoClimbingYet() As String
            Get
                Return ResourceManager.GetString("resNoClimbingYet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You do not know how to swim (yet). .
        '''</summary>
        Friend Shared ReadOnly Property resNoSwimmingYet() As String
            Get
                Return ResourceManager.GetString("resNoSwimmingYet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nothing to kick..
        '''</summary>
        Friend Shared ReadOnly Property resNothingToKick() As String
            Get
                Return ResourceManager.GetString("resNothingToKick", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There is nothing here to pickup. .
        '''</summary>
        Friend Shared ReadOnly Property resNothingToPickup() As String
            Get
                Return ResourceManager.GetString("resNothingToPickup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This town is not ready for visitors yet. Sorry..
        '''</summary>
        Friend Shared ReadOnly Property resNoVisitorsYet() As String
            Get
                Return ResourceManager.GetString("resNoVisitorsYet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You open the door..
        '''</summary>
        Friend Shared ReadOnly Property resOpenDoor() As String
            Get
                Return ResourceManager.GetString("resOpenDoor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Don&apos;t be silly, you can&apos;t open yourself!.
        '''</summary>
        Friend Shared ReadOnly Property resOpenDoorSelf() As String
            Get
                Return ResourceManager.GetString("resOpenDoorSelf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Perhaps you&apos;re looking in the wrong spot. .
        '''</summary>
        Friend Shared ReadOnly Property resPerhaps() As String
            Get
                Return ResourceManager.GetString("resPerhaps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  It is pitch black in here. .
        '''</summary>
        Friend Shared ReadOnly Property resPitchBlack() As String
            Get
                Return ResourceManager.GetString("resPitchBlack", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Kick something. Which direction? .
        '''</summary>
        Friend Shared ReadOnly Property resPromptKickDirection() As String
            Get
                Return ResourceManager.GetString("resPromptKickDirection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  More... .
        '''</summary>
        Friend Shared ReadOnly Property resPromptMore() As String
            Get
                Return ResourceManager.GetString("resPromptMore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Press any key to return. .
        '''</summary>
        Friend Shared ReadOnly Property resPromptPressAnyKey() As String
            Get
                Return ResourceManager.GetString("resPromptPressAnyKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Press a key to continue. .
        '''</summary>
        Friend Shared ReadOnly Property resPromptPressKeyToCont() As String
            Get
                Return ResourceManager.GetString("resPromptPressKeyToCont", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Are you sure you want to quit? (y,N) .
        '''</summary>
        Friend Shared ReadOnly Property resPromptQuit() As String
            Get
                Return ResourceManager.GetString("resPromptQuit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Quit entirely or Restart game? (q/R) .
        '''</summary>
        Friend Shared ReadOnly Property resPromptQuitOrRestart() As String
            Get
                Return ResourceManager.GetString("resPromptQuitOrRestart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you wish to return to the wilderness? (Y/n).
        '''</summary>
        Friend Shared ReadOnly Property resPromptReturnToWilderness() As String
            Get
                Return ResourceManager.GetString("resPromptReturnToWilderness", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select a direction: (1-9).
        '''</summary>
        Friend Shared ReadOnly Property resPromptSelectDirection() As String
            Get
                Return ResourceManager.GetString("resPromptSelectDirection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Which direction?.
        '''</summary>
        Friend Shared ReadOnly Property resPromptWhichDirection() As String
            Get
                Return ResourceManager.GetString("resPromptWhichDirection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to return to game.
        '''</summary>
        Friend Shared ReadOnly Property resReturnToGame() As String
            Get
                Return ResourceManager.GetString("resReturnToGame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You search the surrounding area..
        '''</summary>
        Friend Shared ReadOnly Property resSearchArea() As String
            Get
                Return ResourceManager.GetString("resSearchArea", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You discover a secret door..
        '''</summary>
        Friend Shared ReadOnly Property resSearchSecretDoor() As String
            Get
                Return ResourceManager.GetString("resSearchSecretDoor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You discover a .
        '''</summary>
        Friend Shared ReadOnly Property resSearchTrapDiscover() As String
            Get
                Return ResourceManager.GetString("resSearchTrapDiscover", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You observe the .
        '''</summary>
        Friend Shared ReadOnly Property resSearchTrapObserve() As String
            Get
                Return ResourceManager.GetString("resSearchTrapObserve", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  You have a funny feeling. .
        '''</summary>
        Friend Shared ReadOnly Property resSecretDoorElf() As String
            Get
                Return ResourceManager.GetString("resSecretDoorElf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to apply skill.
        '''</summary>
        Friend Shared ReadOnly Property resSkillsApply() As String
            Get
                Return ResourceManager.GetString("resSkillsApply", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --------------------------------------------------------------------------------.
        '''</summary>
        Friend Shared ReadOnly Property resSkillsBottomBorder() As String
            Get
                Return ResourceManager.GetString("resSkillsBottomBorder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Passive - You are always aware of your surroundings. .
        '''</summary>
        Friend Shared ReadOnly Property resSkillsMsgAwareness() As String
            Get
                Return ResourceManager.GetString("resSkillsMsgAwareness", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Passive - There is nothing for you to climb here..
        '''</summary>
        Friend Shared ReadOnly Property resSkillsMsgClimbing() As String
            Get
                Return ResourceManager.GetString("resSkillsMsgClimbing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Passive - Concentration is key to good spellcasting..
        '''</summary>
        Friend Shared ReadOnly Property resSkillsMsgConcentration() As String
            Get
                Return ResourceManager.GetString("resSkillsMsgConcentration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Passive - This skill ensures your strike is true..
        '''</summary>
        Friend Shared ReadOnly Property resSkillsMsgFindWeak() As String
            Get
                Return ResourceManager.GetString("resSkillsMsgFindWeak", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Passive - You automatically take care of all wounds..
        '''</summary>
        Friend Shared ReadOnly Property resSkillsMsgHealing() As String
            Get
                Return ResourceManager.GetString("resSkillsMsgHealing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to For a brief moment, all is quiet..
        '''</summary>
        Friend Shared ReadOnly Property resSkillsMsgListen() As String
            Get
                Return ResourceManager.GetString("resSkillsMsgListen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Passive - This skill is best exercised by reading..
        '''</summary>
        Friend Shared ReadOnly Property resSkillsMsgLiteracy() As String
            Get
                Return ResourceManager.GetString("resSkillsMsgLiteracy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Passive - This skill is handiest in the wilderness..
        '''</summary>
        Friend Shared ReadOnly Property resSkillsMsgSurvival() As String
            Get
                Return ResourceManager.GetString("resSkillsMsgSurvival", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Passive - If you wish to swim, move through water..
        '''</summary>
        Friend Shared ReadOnly Property resSkillsMsgSwimming() As String
            Get
                Return ResourceManager.GetString("resSkillsMsgSwimming", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skill Name.
        '''</summary>
        Friend Shared ReadOnly Property resSkillsName() As String
            Get
                Return ResourceManager.GetString("resSkillsName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This skill has not been implemented yet..
        '''</summary>
        Friend Shared ReadOnly Property resSkillsNotImplemented() As String
            Get
                Return ResourceManager.GetString("resSkillsNotImplemented", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ranks Bonus Total.
        '''</summary>
        Friend Shared ReadOnly Property resSkillsRBT() As String
            Get
                Return ResourceManager.GetString("resSkillsRBT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ------------------------------------ Skills ------------------------------------.
        '''</summary>
        Friend Shared ReadOnly Property resSkillsTitle() As String
            Get
                Return ResourceManager.GetString("resSkillsTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zzzzz. .
        '''</summary>
        Friend Shared ReadOnly Property resSnoring() As String
            Get
                Return ResourceManager.GetString("resSnoring", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  will it ever end? .
        '''</summary>
        Friend Shared ReadOnly Property resStairsDownEverEnd() As String
            Get
                Return ResourceManager.GetString("resStairsDownEverEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  several creatures follow you. .
        '''</summary>
        Friend Shared ReadOnly Property resStairsFollowSeveral() As String
            Get
                Return ResourceManager.GetString("resStairsFollowSeveral", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  follows you .
        '''</summary>
        Friend Shared ReadOnly Property resStairsFollowsYou() As String
            Get
                Return ResourceManager.GetString("resStairsFollowsYou", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are no downward stairs here..
        '''</summary>
        Friend Shared ReadOnly Property resStairsNoDown() As String
            Get
                Return ResourceManager.GetString("resStairsNoDown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are no upward stairs here. .
        '''</summary>
        Friend Shared ReadOnly Property resStairsNoUp() As String
            Get
                Return ResourceManager.GetString("resStairsNoUp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  the stairs... .
        '''</summary>
        Friend Shared ReadOnly Property resStairsTheStairs() As String
            Get
                Return ResourceManager.GetString("resStairsTheStairs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You return to the overland map. .
        '''</summary>
        Friend Shared ReadOnly Property resStairsUpOverland() As String
            Get
                Return ResourceManager.GetString("resStairsUpOverland", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You return to the surface. .
        '''</summary>
        Friend Shared ReadOnly Property resStairsUpSurface() As String
            Get
                Return ResourceManager.GetString("resStairsUpSurface", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You return to the wilderness. .
        '''</summary>
        Friend Shared ReadOnly Property resStairsUpWilderness() As String
            Get
                Return ResourceManager.GetString("resStairsUpWilderness", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You go .
        '''</summary>
        Friend Shared ReadOnly Property resStairsYouGo() As String
            Get
                Return ResourceManager.GetString("resStairsYouGo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confused.
        '''</summary>
        Friend Shared ReadOnly Property resStatusConfused() As String
            Get
                Return ResourceManager.GetString("resStatusConfused", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  You are confused. .
        '''</summary>
        Friend Shared ReadOnly Property resStatusConfusedMsg() As String
            Get
                Return ResourceManager.GetString("resStatusConfusedMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Your head begins to clear. .
        '''</summary>
        Friend Shared ReadOnly Property resStatusConfusedRecoverMsg() As String
            Get
                Return ResourceManager.GetString("resStatusConfusedRecoverMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  The poison continues to harm you. .
        '''</summary>
        Friend Shared ReadOnly Property resStatusPoisonDamage() As String
            Get
                Return ResourceManager.GetString("resStatusPoisonDamage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poisoned.
        '''</summary>
        Friend Shared ReadOnly Property resStatusPoisoned() As String
            Get
                Return ResourceManager.GetString("resStatusPoisoned", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sleeping.
        '''</summary>
        Friend Shared ReadOnly Property resStatusSleeping() As String
            Get
                Return ResourceManager.GetString("resStatusSleeping", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  You are sleeping. .
        '''</summary>
        Friend Shared ReadOnly Property resStatusSleepingAction() As String
            Get
                Return ResourceManager.GetString("resStatusSleepingAction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  You wake up. .
        '''</summary>
        Friend Shared ReadOnly Property resStatusSleepingWakeUp() As String
            Get
                Return ResourceManager.GetString("resStatusSleepingWakeUp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  You are now visible again. .
        '''</summary>
        Friend Shared ReadOnly Property resStatusVisibleMsg() As String
            Get
                Return ResourceManager.GetString("resStatusVisibleMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use the movement keys to aim your weapon, press [t] to target. Abort with [space] or [z]..
        '''</summary>
        Friend Shared ReadOnly Property resTargetAim() As String
            Get
                Return ResourceManager.GetString("resTargetAim", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There is no door within reach..
        '''</summary>
        Friend Shared ReadOnly Property resThereIsNoDoor() As String
            Get
                Return ResourceManager.GetString("resThereIsNoDoor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  A closed door. .
        '''</summary>
        Friend Shared ReadOnly Property resTileDescriptorDoor() As String
            Get
                Return ResourceManager.GetString("resTileDescriptorDoor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  A section of floor. .
        '''</summary>
        Friend Shared ReadOnly Property resTileDescriptorFloor() As String
            Get
                Return ResourceManager.GetString("resTileDescriptorFloor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  An open door. .
        '''</summary>
        Friend Shared ReadOnly Property resTileDescriptorOpenDoor() As String
            Get
                Return ResourceManager.GetString("resTileDescriptorOpenDoor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Impenetrable rock. .
        '''</summary>
        Friend Shared ReadOnly Property resTileDescriptorRock() As String
            Get
                Return ResourceManager.GetString("resTileDescriptorRock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  A stair leading down. .
        '''</summary>
        Friend Shared ReadOnly Property resTileDescriptorStairsDown() As String
            Get
                Return ResourceManager.GetString("resTileDescriptorStairsDown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  A stair leading upwards. .
        '''</summary>
        Friend Shared ReadOnly Property resTileDescriptorStairsUp() As String
            Get
                Return ResourceManager.GetString("resTileDescriptorStairsUp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Solid stone. .
        '''</summary>
        Friend Shared ReadOnly Property resTileDescriptorStone() As String
            Get
                Return ResourceManager.GetString("resTileDescriptorStone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  trap. .
        '''</summary>
        Friend Shared ReadOnly Property resTrap() As String
            Get
                Return ResourceManager.GetString("resTrap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  You bypass the .
        '''</summary>
        Friend Shared ReadOnly Property resTrapBypass() As String
            Get
                Return ResourceManager.GetString("resTrapBypass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A magical confusion trap..
        '''</summary>
        Friend Shared ReadOnly Property resTrapConfusion() As String
            Get
                Return ResourceManager.GetString("resTrapConfusion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  You feel confused for a brief moment, but it passes. .
        '''</summary>
        Friend Shared ReadOnly Property resTrapConfusionEvade() As String
            Get
                Return ResourceManager.GetString("resTrapConfusionEvade", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Nothing makes sense any more, you are confused. .
        '''</summary>
        Friend Shared ReadOnly Property resTrapConfusionMsg() As String
            Get
                Return ResourceManager.GetString("resTrapConfusionMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An explosive trap..
        '''</summary>
        Friend Shared ReadOnly Property resTrapExplosion() As String
            Get
                Return ResourceManager.GetString("resTrapExplosion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  You hear a click-click-clicking sound. .
        '''</summary>
        Friend Shared ReadOnly Property resTrapExplosionEvade() As String
            Get
                Return ResourceManager.GetString("resTrapExplosionEvade", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  is killed by the explosion. .
        '''</summary>
        Friend Shared ReadOnly Property resTrapExplosionMonsterKilled() As String
            Get
                Return ResourceManager.GetString("resTrapExplosionMonsterKilled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  BOOM! You are caught by an explosion. .
        '''</summary>
        Friend Shared ReadOnly Property resTrapExplosionMsg() As String
            Get
                Return ResourceManager.GetString("resTrapExplosionMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A pit trap..
        '''</summary>
        Friend Shared ReadOnly Property ResTrapPit() As String
            Get
                Return ResourceManager.GetString("ResTrapPit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  You jump to safety as a pit opens at your feet. .
        '''</summary>
        Friend Shared ReadOnly Property resTrapPitEvade() As String
            Get
                Return ResourceManager.GetString("resTrapPitEvade", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Surprise! A pit opens beneath you, and you fall .
        '''</summary>
        Friend Shared ReadOnly Property resTrapPitFall() As String
            Get
                Return ResourceManager.GetString("resTrapPitFall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A poison trap..
        '''</summary>
        Friend Shared ReadOnly Property resTrapPoison() As String
            Get
                Return ResourceManager.GetString("resTrapPoison", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cough Cough... you set off a poison gas trap..
        '''</summary>
        Friend Shared ReadOnly Property resTrapPoisonEffect() As String
            Get
                Return ResourceManager.GetString("resTrapPoisonEffect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  You narrowly avoid a cloud of poisonous gas..
        '''</summary>
        Friend Shared ReadOnly Property resTrapPoisonEvade() As String
            Get
                Return ResourceManager.GetString("resTrapPoisonEvade", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A falling rock trap..
        '''</summary>
        Friend Shared ReadOnly Property resTrapRock() As String
            Get
                Return ResourceManager.GetString("resTrapRock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  A huge rock falls from above, just missing you. .
        '''</summary>
        Friend Shared ReadOnly Property resTrapRockEvade() As String
            Get
                Return ResourceManager.GetString("resTrapRockEvade", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  A huge rock drops on your head from above. .
        '''</summary>
        Friend Shared ReadOnly Property resTrapRockMsg() As String
            Get
                Return ResourceManager.GetString("resTrapRockMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A sleeping gas trap..
        '''</summary>
        Friend Shared ReadOnly Property resTrapSleep() As String
            Get
                Return ResourceManager.GetString("resTrapSleep", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  You feel sleepy for a moment, but it passes. .
        '''</summary>
        Friend Shared ReadOnly Property resTrapSleepEvade() As String
            Get
                Return ResourceManager.GetString("resTrapSleepEvade", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A brief sensation passes over you. .
        '''</summary>
        Friend Shared ReadOnly Property resTrapSleepResistElf() As String
            Get
                Return ResourceManager.GetString("resTrapSleepResistElf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Uhoh, strange magic is... Zzzzzzzz... .
        '''</summary>
        Friend Shared ReadOnly Property resTrapSleepResistFail() As String
            Get
                Return ResourceManager.GetString("resTrapSleepResistFail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You feel sleepy for a moment, but it passes. .
        '''</summary>
        Friend Shared ReadOnly Property resTrapSleepResistHalfElf() As String
            Get
                Return ResourceManager.GetString("resTrapSleepResistHalfElf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A snake pit trap..
        '''</summary>
        Friend Shared ReadOnly Property resTrapSnake() As String
            Get
                Return ResourceManager.GetString("resTrapSnake", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  You hear a muffled hissing sound nearby. .
        '''</summary>
        Friend Shared ReadOnly Property resTrapSnakeEvade() As String
            Get
                Return ResourceManager.GetString("resTrapSnakeEvade", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Suddenly you are surrounded by snakes. .
        '''</summary>
        Friend Shared ReadOnly Property resTrapSnakeMsg() As String
            Get
                Return ResourceManager.GetString("resTrapSnakeMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A magical teleportation trap..
        '''</summary>
        Friend Shared ReadOnly Property resTrapTeleport() As String
            Get
                Return ResourceManager.GetString("resTrapTeleport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  You briefly feel as though you belong somewhere else. .
        '''</summary>
        Friend Shared ReadOnly Property resTrapTeleportEvade() As String
            Get
                Return ResourceManager.GetString("resTrapTeleportEvade", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Suddenly you are somewhere else. .
        '''</summary>
        Friend Shared ReadOnly Property resTrapTeleportMsg() As String
            Get
                Return ResourceManager.GetString("resTrapTeleportMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use the movement keys to position the cursor. Abort with [SPACE] or [Z]..
        '''</summary>
        Friend Shared ReadOnly Property resUseMovementKeys() As String
            Get
                Return ResourceManager.GetString("resUseMovementKeys", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  ...and we&apos;re walking... .
        '''</summary>
        Friend Shared ReadOnly Property resWalking() As String
            Get
                Return ResourceManager.GetString("resWalking", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  You pick up the .
        '''</summary>
        Friend Shared ReadOnly Property resYouPickUp() As String
            Get
                Return ResourceManager.GetString("resYouPickUp", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
